### PR TITLE
Mark homework

### PR DESCRIPTION
**Pull request by markrobinsonuzh**
- made an orchestrator template

### CODE REVIEW

**Comment by ansonrel** [comment]
Thanks for the PR! Some ideas for improvement: 
-  maybe remove the `iris` names from the example blocks in the `.gitlab-ci.yml` to avoid confusion ? 
- Second part of the homeworks: could you add the variables that are currently in the triggered projects into the orchestrator (`OMNIBENCHMARK_NAME`, `USERNAME `etc.) ? They could for instance be defined in the very first block of `.gitlab-ci.yml` and  then be invoked in the example trigger blocks that you already created (alongside `CI_UPSTREAM_PROJECT` etc.). 
- the 'orchestrator' section from the `manifest` lists some variables (that the user can define during project creation) but none of them is really used from what I see. 
Maybe you could replace them with the variables from my former point ? Hint: some variables such as project name and namespace are automatically defined (Renku discuss this in their [doc about templates](https://renku.readthedocs.io/en/latest/reference/templates.html#manifest-yaml))

**Comment by markrobinsonuzh** [comment]
- removed all occurrences of `iris`
- updated the `manifest.yaml` to have more variables exposed

**Comment by markrobinsonuzh** [comment]
- `OMNIBENCHMARK_NAME` and `TRIPLESTORE_URL` specified by the user (in the web tool to create a new Renku project) are now captured in the `variables:` section of `.gitlab-ci.yml` of the created repo

**Comment by markrobinsonuzh** [comment]
I tested this on a fork (because of my borked cache) and it works ok. So, I'd be happy to know if there is more to do for this HW.

**Comment by ansonrel** [comment]
Seems all good, thank you! I'll merge the branch.

**Pull request merged**
